### ISSUE TITLE
Bifrost query std::bad_alloc error

### ISSUE THREAD

**Issue by ptrebert** [pmelsted/bifrost#21]
Hi Guillaume,
I am running Bifrost built from source (26746a1), and successfully build a gfa file containing several human assemblies. For "playing around", I want to query that graph with annotated regulatory regions (~20 million, as FASTA). I get the following error output shortly after the "Querying graph" stage is reached:
```
ColoredCDBG::read(): Reading graph.

CompactedDBG::read(): Reading graph from disk
KmerStream::KmerStream(): Start computing k-mer cardinality estimations

CompactedDBG::read(): Finished reading graph from disk
ColoredCDBG::read(): Reading colors.

DataStorage::read(): Reading color sets from disk
ColoredCDBG::read(): Joining unitigs to their color sets.
ColoredCDBG::search(): Querying graph.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```
```
Bifrost query -g hsa_test.gfa \
-q annotation/reg_clusters.hg38.fasta \
-o test_output \
-e 0.95 \
-f hsa_test.bfg_colors \
-t 48 \
-n -v 
```
The machine has 1.5 TB of main memory (I am currently the only user). Right now, I am testing the same command with only a single thread.

Best,
Peter

**Comment by ptrebert** [comment]
Update: Bifrost query is still running (using a single thread), now for 12.5 hrs, memory usage seems to be constant at around 24 GB

**Comment by GuillaumeHolley** [comment]
Hi @ptrebert,

Thanks for reaching out. In normal time, I would have said "you don't have enough RAM" but with 1.5 TB, it don't think it is the issue :) Could you give me a few more information:

- Number of unitigs and k-mers in your graph?
- Numbers of colors in your graph?
- How long are you queries? Can you give me something like an average length or N50? If the lengths are very diverse, could you provide me the length of the longest query?

**Comment by ptrebert** [comment]
Hi Guillaume,
I hope I got the right numbers for you:
- unitigs: ~ 55M
- kmers: ~ 2.5B
- colors: 5 (here I am sure...)
- query stats (min/median/mean/max): 50, 410, 450, ~105k

Single-thread Bifrost is still running (close to 17h now), memory consumption hasn't changed.
Thanks for looking into this.

+Peter

**Comment by GuillaumeHolley** [comment]
Hi again,

Thanks for these info. I don't see anything that is particularly annoying here, even the 105k query shouldn't be a problem for Bifrost. Maybe an issue is with the inexact mode `-n` combined with the colors. I will have a look at it this weekend and get back to you at the beginning of next week ;)

**Comment by ptrebert** [comment]
Great, thanks for the effort.
Single-threaded analysis still running fine...

**Comment by ptrebert** [comment]
Still running, ~40.5 hours now...

**Comment by GuillaumeHolley** [comment]
Hi @ptrebert,

I had a look in the functions doing the inexact k-mer search per color, particularly all allocations and deallocations but everything *seemed* in order. I couldn't reproduce the issue myself. The code at this point is rather vast and unless I know what I am looking for, it's going to be complicated to find this bug. Would there be any chance you could share with me your graph, colors and queries?

On the positive side, I found an issue which prevented Bifrost from aborting the querying as soon as  threshold *e* was reached when using colors and inexact k-mers. If your single-thread querying is still running, you might want to give it a new shot. Also, by counting the numbers of lines in the output TSV file, you can see how many queries Bifrost has processed so far.

**Comment by GuillaumeHolley** [comment]
I would appreciate if you could also give a shot to the multi-threaded querying again. I did change a couple of things and who knows.

**Comment by ptrebert** [comment]
That's some interesting news. About sharing the dataset: half of the data has been published, so I guess for debugging purposes, that's fine. You happen to have some space I can push to from the command line?
Regarding testing the updated version: I'll give it a try, but based on your remark concerning number of queries processed, I noted that the output file has still zero lines in it. Is there maybe something else wrong? According to top, Bifrost is keeping one CPU core busy at 100% all the time, and has been doing so for ~66 hours now. Does that seem strange?

**Comment by GuillaumeHolley** [comment]
I had one similar report last week about someone who was trying to build the colored graph but it was taking a very long time during the coloring phase, a lot more than usual. Your issue is that apparently, the querying is stuck on one of the very first queries. Combining both, I assume there is something wrong with the recent changes I made to the color container in Bifrost. As a precaution, I rolled back those changes yesterday. Unfortunately, it means you will have to redo a new graph if you want to give it a new shot :(
Regarding the sharing of your dataset, that would be very kind. If the unpublished part of your data is of concerned, maybe it is enough I (publicly) state here I would use them only for the debugging purpose of that particular problem. Right now, I don't have space that I can share but I will try to arrange something next week. Before going there, maybe you could give a shot to a new building + querying with the latest commit (just pushed it) and see if you still have this issue?

Thank you for your time and your patience.
Guillaume

**Comment by ptrebert** [comment]
Ok, I am killing the single-threaded run now (~85 hours, still zero lines in the output file) and rebuild/restart with the current master.
Thanks for all your effort!

**Comment by ptrebert** [comment]
Graph building with the latest master finished w/o issues, the querying is still broken, though. I get the same `std::bad_alloc` as before. I also started a single-threaded run to check if it generates output this time, but also that does not seem to have changed (the output file has been create about 30 minutes ago and is still empty)

**Comment by GuillaumeHolley** [comment]
Damn it.

I just sent you an email to see how we can share your data such that I can figure out what's wrong.

**Comment by GuillaumeHolley** [comment]
Hi @ptrebert,

Just a small update on our progress.

It took us an ridiculous amount of time to download the files from the storage account we had set up. I think their connection isn't particularly stable during the week and after a few gigabytes downloaded, the connection would be interrupted or the download would be stopped. We even thought we had it done after a wget trick and as it turns out, the graph file was corrupted... Anyway, I managed to download everything this week-end and I also ended up being stuck in single-thread mode with an empty output. Everything is now running in debug mode with valgrind on our cluster.

**Comment by ptrebert** [comment]
Ok, thanks for the update, and good to hear that you could reproduce the bug! I keep my fingers crossed that you can track this down quickly now

**Comment by GuillaumeHolley** [comment]
Hi @ptrebert ,

I finally figured out the issue without Valgrind and it is a very silly bug. I decided to take a quick look at your queries and I noticed that they mix upper case and lower case characters. Internally, Bifrost processes upper case characters only so when processing input sequences, the API changes all characters to upper case. But I did not implement that in the *k*-mer search functionality... Anyway, I fixed it :) Try it and let me know how it goes.

**Comment by ptrebert** [comment]
Ok, that sounds simple enough, glad that you fixed it - I let you know if it works now ;-)

**Comment by ptrebert** [comment]
@GuillaumeHolley 
Good news, my test run with the fixed version is producing output (with 48 threads); I keep this issue open until it finishes, but it looks all good right now. Thanks for the fix.

**Comment by ptrebert** [comment]
The test run finished successfully. Thanks again, closing this now
