### ISSUE TITLE
How to construct de Bruijn graphs using bifrost without reference sequence?

### ISSUE THREAD

**Issue by xiekunwhy** [pmelsted/bifrost#26]
Hi,

For non-model species, how to construct de Bruijn graphs using bifrost without reference sequence?

Best,
Kun

**Comment by GuillaumeHolley** [comment]
Hi Kun,

Since you don't have a reference sequence, I assume you want to build the de Bruijn graph from reads. Hence use the option `-s` to input your reads (you can see all the options with `--help`). By default, `-s` will construct the de Bruijn graph from all k-mers occurring twice or more in the input reads (k-mers with once occurrence are considered to result from a sequencing error).

Guillaume

**Comment by GuillaumeHolley** [comment]
I will close this issue now. Let me know if you need more information.

Guillaume
