### ISSUE TITLE
Corrupted tsv when querying colored graph?

### ISSUE THREAD

**Issue by phiweger** [pmelsted/bifrost#32]
Hi,

I try to query a lot of k-mers (about 5 mio) in a colored graph (based on some reference genomes). All default settings k=31, query k-mers are also 31.

The returned tsv has rows of different lengths. My suspicion is that Bifrost writes in parallel to a single file and somehow there is no write lock so that one process writes to the file even though another one has not finished. Could this be possible?

Thanks!

**Comment by GuillaumeHolley** [comment]
Hi @phiweger,

That's annoying, sorry about that. There is obviously a write lock but it is possible it is not used properly. I had some issues with this before so I will make some more testing soon. I would appreciate if you had a minimum example of graph + colors + queries for which the issue occurs that I could use.

**Comment by phiweger** [comment]
Sure -- https://osf.io/eyunk/

**Comment by GuillaumeHolley** [comment]
Hi @phiweger,

I downloaded your files and I performed a simple querying using most default parameters:
`Bifrost query -v -t 16 -g graph.gfa -f graph.bfg_colors -q kmers.fasta -o res1`

I used 16 threads to "maximize" my chance of messing with the output. I then counted the number of fields in the header of the TSV output:
`head -n 1 res1.tsv | awk '{print NF}'`
which gives 1708.

Then I searched for a line having a different number of fields than 1708:
`awk '{if (NF!=1708) print NR " " NF}' res1.tsv`
and there was no output, meaning that my output file `res1.tsv` has the correct length over each line. I tried the same experiment with 32 threads but unfortunately (or fortunately?) ended up with a consistent result too. 

I'm afraid that you have the version 1.0.3 installed on your system, which you probably obtained from conda, which suffered from issue #23. This has since been fixed but the conda recipe hasn't been updated since that time as I just made a release for version 1.0.4 recently. Is it what happened?

Otherwise, could you tell me:
- How did you install Bifrost (conda or source)?
- Which OS and compiler are you using for the experiment?
- How many threads are you using for the experiment?
- How many lines do you have in your faulty TSV output file?
- How many fields do you have in a row having an abnormal number of fields?

**Comment by GuillaumeHolley** [comment]
I actually don't think anymore that the problem is conda. I was trying to update the conda recipe and realized that the recipe has been automatically updated to the latest version by the BioCondaBot. Same with Brew. Can you do, in addition to my previous questions, a `Bifrost --version` for me?

**Comment by phiweger** [comment]
Indeed!

```bash
docker run --cpus 8 -v $PWD:/data nanozoo/bifrost:1.0.3--749395e Bifrost
# Bifrost 1.0.3
```

I installed Bifrost by building it inside a Docker container (my [last build](https://hub.docker.com/r/nanozoo/bifrost) is actually v1.0.4 but I kept using an older one v1.0.3 -- thanks a lot for your quick help!

Kindest regards
