### ISSUE TITLE
mappedSequenceToString: incorrect behavior when strand=false and um.len > 1?

### ISSUE THREAD

**Issue by lrvdijk** [pmelsted/bifrost#33]
Hi,

Imagine having a unitig with sequence `TCGAAATCAGT` (reverse complement: `ACTGATTTCGA`).

When doing `ccdbg.find(Kmer("ACTGA"))` (k=5), you'll get a `UnitigMapping` with `um.dist = 6` and `um.len = 1, um.strand = false`, because ACTGA is the first k-mer of the reverse complement of the TCGAAATCAGT unitig, and thus the last k-mer (pos=6) of the unitig in forward orientation.

When `len=1`, mappedSequenceToString works fine, and returns `ACTGA`. If we manually change the um.len property, the behaviour will be incorrect:

```cpp
        // Kmer in reverse orientation with respect to the unitig
        auto um = test_graph.find(Kmer("ACTGA"));
        std::cerr << um.referenceUnitigToString() << std::endl;
        std::cerr << um.mappedSequenceToString() << std::endl;
        std::cerr << "Dist: " << um.dist << " len: " << um.len << " Strand: " << um.strand << std::endl;

        um.len = 2;
        std::cerr << um.referenceUnitigToString() << std::endl;
        std::cerr << um.mappedSequenceToString() << std::endl;
        std::cerr << "Dist: " << um.dist << " len: " << um.len << " Strand: " << um.strand << std::endl;

        um.len = 7;
        std::cerr << um.referenceUnitigToString() << std::endl;
        std::cerr << um.mappedSequenceToString() << std::endl;
        std::cerr << "Dist: " << um.dist << " len: " << um.len << " Strand: " << um.strand << std::endl;

        // Test in forward orientation
        um = test_graph.find(Kmer("TCGAA"));
        um.len = 7;
        std::cerr << "Forward orientation:" << std::endl;
        std::cerr << um.referenceUnitigToString() << std::endl;
        std::cerr << um.mappedSequenceToString() << std::endl;
        std::cerr << "Dist: " << um.dist << " len: " << um.len << " Strand: " << um.strand << std::endl;
```

Output:
```
TCGAAATCAGT
ACTGA
Dist: 6 len: 1 Strand: 0
TCGAAATCAGT
TACTGA
Dist: 6 len: 2 Strand: 0
TCGAAATCAGT
TTTTTTACTGA
Dist: 6 len: 7 Strand: 0
Forward orientation:
TCGAAATCAGT
TCGAAATCAGT
Dist: 0 len: 7 Strand: 1
```

As you can see, when the query k-mer is in reverse orientation, the mappedSequenceToString prepends T's to the k-mer, indicating of empty `Kmer` objects. This is likely because dist is already at 6, and when increasing dist, it returns empty kmers because we're already at the end of the unitig.

When doing the same thing with a query k-mer in forward orientation, manually changing um.len works as expected.

**Comment by GuillaumeHolley** [comment]
Hi @lrvdijk ,

As you said, if you have `um.dist=6` and `um.len=1`, you are already on the last k-mer of the unitig (in forward direction). Increasing `um.len` such that it is larger than 1 means that you are trying to extract a substring which is beyond the end of the unitig. And this is undefined behavior, just like using `string::substr()` on a length extending beyond the end of the string. In your case, it prepends the k-mer with Ts but this is garbage, it could equally likely preprend your k-mer with anything else or just crash your program.

**Comment by lrvdijk** [comment]
Yes, my point is more, shouldn't the behavior change when strand = false? So to build a mapped sequence when strand = false, we should enumerate dist...(dist-len+1) (i.e. decreasing) instead of dist...(dist+len)

**Comment by lrvdijk** [comment]
I've created a workaround, by first reverse complementing the sequence and then taking a substring from it:
https://github.com/lrvdijk/bifrost/commit/85107dd274479c30543c530310c0b86714a733ba#diff-a60c6453651403f4137a276fe2a59ee9L53

```
TCGAAATCAGT
ACTGA
Dist: 6 len: 1 Strand: 0
TCGAAATCAGT
ACTGAT
Dist: 6 len: 2 Strand: 0
TCGAAATCAGT
ACTGATTTCGA
Dist: 6 len: 7 Strand: 0
Forward orientation:
TCGAAATCAGT
TCGAAATCAGT
Dist: 0 len: 7 Strand: 1
```

**Comment by GuillaumeHolley** [comment]
Hey @lrvdijk,

I might be incorrect but it seems to me you are replacing a problem with another one. Using your method, if you do `um.dist = 0` and `um.len = 2`, you program will do the exact same undefined behavior as before which is extending over the end of a string. Furthermore, you have now two behaviors to manage for UnitigMaps: one in forward (increase) and one in reverse-complement (decrease). In Bifrost, all methods working with `UnitigMap`, so mostly everything, use `dist `and `len` with respect to the forward strand, which keeps things simple. The intention is basically to mimic the `string::substr(dist, len)` from C++. Finally, in your method, on [line 54](https://github.com/lrvdijk/bifrost/blob/85107dd274479c30543c530310c0b86714a733ba/src/UnitigMap.tcc#L54), you end up reverse-complementing the whole unitig first and doing a substring of it afterwards. This can be a performance issue if you extract tiny substrings from large unitigs because you have the extra computation of reverse-complementing something that you won't use. Use case here is extracting head/tail k-mers from unitigs for navigation purposes.

**Comment by lrvdijk** [comment]
Hmm you're right, and yeah reverse complementing the whole unitig is far from an ideal solution. Anyway, good to know that `dist` and `len` should always be with respect to the forward strand, might need to check if I follow that assumption in my Python bindings too.

Closing for now, thanks!
