### ISSUE TITLE
Intuition behind choosing minimizer length

### ISSUE THREAD

**Issue by Colelyman** [pmelsted/bifrost#4]
Thanks @GuillaumeHolley and @pmelsted for such an excellent application! I have been using it for the past couple months and it has worked very well.

I just wanted to reach out to hear your thoughts on how the minimizer length, `m`, affects performance. I understand that by definition `m < k` and with a very small `m` you will have lots of "collisions" (not sure if that is the right term here) and I believe this will lead to slower performance. 

Right now, I don't necessarily see any negative performance results for choosing a `m` that is fairly close to the `k`. I definitely could be missing something though.

Any thoughts or previous experience are welcome!

Thanks,
Cole

**Comment by GuillaumeHolley** [comment]
Hi Cole, 

Glad to hear you like Bifrost :)

It is a very good question and you are making the right assumptions here. As you already know, choosing the length of minimizers (g) is a trade-off between running time and memory. As you said, having very short g-mers results in a low memory usage but longer running times as you get fewer minimizers to store and index but they occur more often in unitigs. Obviously, having long minimizers works the other way around.
Now, having g-mers nearly as long as your k-mers means that you end-up storing nearly two de Bruijn graphs at once because the minimizer hash-table is an approximation of the uncompacted dBG (one g-mer is nearly one k-mer). It's completely fine if memory is not a concern and you really want to get Bifrost running as fast as you can.

I don't have any benchmarks for the minimizer length for each k-mer length but as a rule of thumb:
- 23<=g<=25 for k>31
- g=k-8 for k<=31

I was told that g=17 makes wonders for k=21 and k=25.

Guillaume

**Comment by Colelyman** [comment]
That is helpful! Thank you

**Comment by GuillaumeHolley** [comment]
Hi Cole,

Just to let you know that I have pushed a new version of Bifrost that automatically uses g=k-8 for large enough k-mers (k>=15). You can play around that value (max. +/- 4) if you want to favor memory over running time or the other way around.
