### ISSUE TITLE
Plans to submit to Bioconda?

### ISSUE THREAD

**Issue by rpetit3** [pmelsted/bifrost#7]
Hello! 

Do you have plans to submit Bifrost to Bioconda? I could help out, but in order to do so a more recent release would need to be created.

Thanks!

**Comment by GuillaumeHolley** [comment]
Hi!

Yes, we definitely have plans to submit Bifrost to Bioconda. We've been postponing it for quite some time but I think that now you're are asking, it is time :) I am planning to push a rather big update of Bifrost next week and I think it should be the version available on Bioconda. So as soon as it is online, I tag a release and prepare the Bioconda submission, what do you think?

I will keep the issue open in the meantime.
Thanks for the suggestion!

Guillaume

**Comment by winni2k** [comment]
It would be great to see a bioconda relase! Conda packaging can be a nightmare, so I'd be happy to help as well.

**Comment by GuillaumeHolley** [comment]
Thanks for the offer, I will definitely contact you if I run into some issues with the Conda packaging. Unfortunately, I will have to delay the release of the next Bifrost update, and hence its conda release, till the end of February to make space for some more testing.

**Comment by GuillaumeHolley** [comment]
So as it turns out, making a Conda package is really a nightmare. My extremely simple recipe fails because Cmake cannot pass one of his checks. I've been digging the problem a lot and if I am not wrong, there is nothing I can do because it is an issue with Conda itself. I have opened an issue with them [(here)](https://github.com/conda/conda/issues/9741) if you want to have a look. I would appreciate any suggestions on the problem.

**Comment by johnlees** [comment]
I should have checked the issues here first, but I have made a recipe for bioconda which will be added soon:
https://github.com/bioconda/bioconda-recipes/pull/21255

So should soon be installable with `conda -c bioconda bifrost` (includes binary and libraries) 

I couldn't get the OS X build to work as there seemed to be some missing header in pthreads, so if anyone knows how to fix it, that would be great (but from what I could tell could be an OS X/command line tools version issues, which would be difficult to fix)

**Comment by GuillaumeHolley** [comment]
Hi @johnlees,

Thank you for that, that's amazing! I actually submitted a bioconda recipe some time ago (https://github.com/bioconda/bioconda-recipes/pull/20840) but I ended up having issues to with the MacOS build as well and I didn't have the time to look at the issue afterwards. I have a couple more things in my PR compared to yours, an extra file to deal with some cmake issues and some more code for Zlib, do you mind having a look at my PR and eventually update yours?

Thanks.
Guillaume

**Comment by johnlees** [comment]
Yeah, looks like we ran into the same issue with the OS X build, I think it is likely that the version on their CI isn't new enough to support this. You can just skip the OS X build to get it to pass, which is what I did (but there is the homebrew package, so hopefully not a big issue).

A few questions on your additions:
- In the `build.sh` is the export of various Make variables necessary? It seems to work ok without them, as I think they are generally set correctly when you include the conda compilers.
- I forgot about `Release`, but perhaps this is the default? The compiler command lines look like:
compiling: `$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc -DMAX_KMER_SIZE=32 -I$SRC_DIR/src  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/bifrost-1.0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -std=c11 -march=native -DXXH_NAMESPACE=BIFROST_HASH_ -O3 -DNDEBUG   -O3 -o CMakeFiles/bifrost_static.dir/roaring.c.o   -c $SRC_DIR/src/roaring.c`
linking: `$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/bifrost-1.0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -std=c++11 -march=native -DXXH_NAMESPACE=BIFROST_HASH_ -O3 -DNDEBUG  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -rdynamic CMakeFiles/Bifrost.dir/Bifrost.cpp.o  -o Bifrost  -Wl,-rpath,$SRC_DIR/build/src: libbifrost.so -lpthread -lz`
which both have `-O3`
- Similarly for the `cross-linux.cmake` file, I'm not sure why this is needed?
- I think run machines always have `zlib`, so you don't need to specify it (if I remember correctly)

Cheers,
John

**Comment by GuillaumeHolley** [comment]
Hey John,

Thanks for your feedback. I'm no Conda expert so here are my answers to take with a grain of salt :)

- I added the exports because I noticed that when you install Bifrost from source on MacOS and you did not install Xcode previously, the Bifrost library cannot be found because all the standard environment paths are not set. I guess the point of conda is to not have those issues so I think the exports can be skipped. Also, it seems we are skipping the MacOS build completely now until we can fix this issue. So it's fine ;)
- Release is default indeed so it can be removed.
- I think this one is important. Originally, I encountered some issues with Cmake while trying to make the recipe work. As it turns out, I was at fault but I've learned a lot about how Conda interacts with Cmake and I found this [link](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#an-aside-on-cmake-and-sysroots) in the Conda documentation explaining how to overcome issues with the Cmake toolchain. I don't think it cost anything to add the file and it will likely avoid us some problems in the future.
- You must specify zlib and pthread in your recipe to make sure Conda uses the libraries from the host plateform and not from the build plateform [(doc)](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#an-aside-on-cmake-and-sysroots). It will work most of the time otherwise but it's likely the recipe will fail for someone at some point.

**Comment by johnlees** [comment]
Ah, great, thanks for clarifying! Looks like I misunderstood the zlib and pthreads usage, and I will also add the cmake file.

**Comment by GuillaumeHolley** [comment]
Looks like the Bifrost recipe passed all the tests and is now merged :)
Thanks @johnlees for putting your time and efforts into this. I will close this issue now but I think we should keep in mind a way to have the MacOS version running at some point.
